// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5gmaimgUu5NZmVShmvUYF8lkaS8-y6Lg',
    appId: '1:364580516304:web:74d5a62eb3b268671249d5',
    messagingSenderId: '364580516304',
    projectId: 'project-1-9fedc',
    authDomain: 'project-1-9fedc.firebaseapp.com',
    storageBucket: 'project-1-9fedc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYEzwYUJ3KdRmkjWZ3kMF71IXR6Ga7RZE',
    appId: '1:364580516304:android:14a766596b74cb301249d5',
    messagingSenderId: '364580516304',
    projectId: 'project-1-9fedc',
    storageBucket: 'project-1-9fedc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1-nomUNP9UcpKcCbbFYX7cm0mnQ5aLsg',
    appId: '1:364580516304:ios:36a5f50aae065b361249d5',
    messagingSenderId: '364580516304',
    projectId: 'project-1-9fedc',
    storageBucket: 'project-1-9fedc.firebasestorage.app',
    iosBundleId: 'com.example.estore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1-nomUNP9UcpKcCbbFYX7cm0mnQ5aLsg',
    appId: '1:364580516304:ios:36a5f50aae065b361249d5',
    messagingSenderId: '364580516304',
    projectId: 'project-1-9fedc',
    storageBucket: 'project-1-9fedc.firebasestorage.app',
    iosBundleId: 'com.example.estore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5gmaimgUu5NZmVShmvUYF8lkaS8-y6Lg',
    appId: '1:364580516304:web:d9dd18da7e1084781249d5',
    messagingSenderId: '364580516304',
    projectId: 'project-1-9fedc',
    authDomain: 'project-1-9fedc.firebaseapp.com',
    storageBucket: 'project-1-9fedc.firebasestorage.app',
  );
}
